package managment.actionManagement;

public enum ActionType {
    GET_DAMAGE, GET_HEALING, DEAL_DAMAGE
    , ATTACK, TREATMENT, USED_SKILL
    , ZERO_HP, NEGATIVE_HP, POSITIVE_HP,
    LEVEL_UP, LEVEL_DOWN,
    START_TURN, END_TURN,
    SWAP_HEROES, USED_BONUS
}
